#!/bin/bash

#ZAP_HOME=/opt/zaproxy
#ZAP_JAR="zap-2.11.1.jar"
#TARGET_URL="http://example.com/"
#TARGET_REPORT="/tmp/test-report.html"

failure_code() {
    local url=${1:-http://localhost:8080}
    local code=${2:-500}
    local status=$(curl --head --location --m 5 --write-out %{http_code} --silent --output /dev/null ${url})
    [[ $status == ${code} ]] || [[ $status == 000 ]]
}

failure_code "${TARGET_URL}" && echo "  [x] Connection refused ${TARGET_URL}" && exit 1

echo "  [.] Start OWASP ZAP scan ${TARGET_URL} .. "

java -jar ${ZAP_HOME}/${ZAP_JAR} -cmd -quickurl ${TARGET_URL} -quickprogress -quickout ${TARGET_REPORT}
if [ $? -eq 0 ]; then
	echo "  [+] OK"
	[ -e ${TARGET_REPORT} ] && echo "  [+] Report (${TARGET_URL}): ${TARGET_REPORT} ready."
else
	echo "  [x] FAILURE"
	echo "  [-] Unable to scan ${TARGET_URL}"
fi